src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/ServiceHelper.cs
`ServiceController` throws an exception if you attempt to start/stop a service when it is already in the desired state. We want our API to be idempotent in this case instead.
=> Only run service actions in specific states

src/ScaleUnitManagement/Utilities/AxDeployment.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/WorkloadInstanceManager.cs, src/ScaleUnitManagementTests/AxDeploymentTest.cs
Changing the effective date on the workloads when they are installed.
If the version is 10.0.21 or earlier, 5 minutes are added to the time, such that the installation succeeds first and the movement jobs will get created.
=> Set temporal assignments' effective date in the future =< 10.0.21

src/ScaleUnitManagement/Utilities/Config.cs, src/ScaleUnitManagement/Utilities/ScaleUnitMnemonicCalculator.cs, src/ScaleUnitManagementTests/ScaleUnitMnemonicCalculatorTest.cs
// Not tested
Checking when the config is loaded if the ScaleUnitId is valid, i.e. if it lies within 1 and 1000 or is a hub.
resolves #63
=> Checking if the scaleUnitId is valid

src/CLI/Program.cs, src/CLI/SetupTools.cs, src/CLI/SyncDB.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Common/RunDBSync.cs
Added a new option to the start menu: "Setup Tools". From here the user can sync the HubDB, or select a ScaleUnit to sync. The scale units only appear if UseSingleOneBox is true.
=> Creating Setup Tools menu, which allows syncing both the Hub and the Spoke

src/CLI/MoveWorkloads.cs
The scale units were being sorted while the program was iterating through them. The sort was unnecessary, so it has been removed to fix the issue. This has been tested by running all the local tests and manually setting up, installing and moving workloads in a singleOneBoxEnvironment.
#patch
resolves #73
=> Fixing movement of workloads

src/ScaleUnitManagement/ScaleUnitFeatureManager/Common/AddToolClientToSysAADClientTable.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Common/RunDBSync.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Hub/AddMESFeatureFlight.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Hub/EnableNumberSequenceTableChangeTracking.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/ScaleUnit/ClearProblematicTables.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/ScaleUnit/ConfigureScaleUnit.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/ScaleUnit/EnableDbChangeTracking.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/CertificateStoreHelper.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/CommandExecutor.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/IISAdministrationHelper.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/SqlQueryExecutor.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/WebConfig.cs, src/ScaleUnitManagement/ScaleUnitManagement.csproj
CommandExecutor can now execute commands without PowerShell using `Process.Start`.
`Invoke-SqlCmd` has been removed. Instead `SqlCommand` is used to query the database.
Resolves remaining items on #10
=> Replace use of Powershell scripts using SqlClient and Process.Start

src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/CommandExecutor.cs
Processes with output files had streams that were not closed after running the process. This caused errors when trying to write to the same file twice. Tested manually on a SingleOneBox environment.
Resolves #80 
#patch
=> Close output file after process has exited

src/ScaleUnitManagement/WorkloadSetupOrchestrator/HubWorkloadInstaller.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/WorkloadMover.cs
Asynchronously make an API request for every workloadInstance when writing workloads, instead of writing all of them at the same time. Manually tested in the SingleOneBox environment.
closes #82 
#patch
=> Make seperate API write request for every workload

src/CLI/SetupTools.cs, src/CLI/SetupToolsOptions/CleanUpStorageAccount.cs, src/CLI/SetupToolsOptions/ImportWorkloadBlob.cs, src/CLIFramework/CLIMenu.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/StorageAccountManager.cs
Using a SAS token, the user can copy an Azure blob into one of the scale unit containers.
Tested manually in the singleOneBox environment by importing workloads between hub and spoke, with SAS tokens created on the Azure Storage page.
=> Add capability to import workloads from different Azure Storage

src/ScaleUnitManagement/ScaleUnitFeatureManager/Utilities/IISAdministrationHelper.cs
When starting IIS site AOSServices, the IIS services must be running. This change will start it every time, and if it is already started it will just state that and move on.
#patch
closes #62 
After stopping the services and making sure that W3SVC is not running, this is the output:
=> Starting the W3SVC service in case it is stopped

src/ScaleUnitManagement/WorkloadSetupOrchestrator/WorkloadDeleter.cs
Tested by deleting all workloads in the singleOneBox environment.
Resolves #87 
#patch
=> Make separate AOS calls for every instance deleted

src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/WorkloadInstanceManager.cs
=> Use DateTime from AddMinutes

.github/workflows/dotnet-core-release.yml, src/Directory.Build.props
Looking into a customer environment, I noticed that our binaries are missing certain details that make debugging easier (versioning, for one).
This PR adds versioning and a few more details to assemblies generated for the releases and if built locally in VS.
=> Add assembly details, with tagged version on CI in main

src/CLI/ConfigureEnvironment.cs, src/CLI/DeleteWorkloads.cs, src/CLI/EnableScaleUnitFeature.cs, src/CLI/ManageWorkloadDataPipeline.cs, src/CLI/RootMenu.cs, src/CLI/SetupTools.cs, src/CLI/SetupToolsOptions/CleanUpStorageAccount.cs, src/CLI/SetupToolsOptions/DisableScaleUnitFeature.cs, src/CLI/SetupToolsOptions/ImportWorkloadBlob.cs, src/CLI/SetupToolsOptions/SyncDB.cs, src/CLI/SetupToolsOptions/UpdateScaleUnitId.cs, src/CLI/WorkloadInstallationMenu.cs, src/CLI/WorkloadInstallationOptions/InstallWorkloads.cs, src/CLI/WorkloadInstallationOptions/WorkloadsInstallationStatus.cs, src/CLI/WorkloadMovementMenu.cs, src/CLI/WorkloadMovementOptions/WorkloadMovementStatus.cs, src/CLIFramework/CLIController.cs, src/CLIFramework/CLIScreen.cs, src/CLIFramework/MultiSelectScreen.cs, src/CLIFramework/SingleSelectScreen.cs, src/ScaleUnitManagementTests/CLITests/MultiSelectScreenTest.cs, src/ScaleUnitManagementTests/CLITests/SingleSelectScreenTest.cs, src/ScaleUnitManagementTests/ScaleUnitManagementTests.csproj
Create two different types of screens, the single select and the multi select used for selecting steps.
Tests included for the two screen types.
#minor
Resolves #75
=> Allow user to choose a subset of steps to run

src/CLI/SetupTools.cs, src/CLI/SetupToolsOptions/PerformEmergencyTransitionToHub.cs, src/CLI/SetupToolsOptions/TransitionToHub.cs, src/CLI/WorkloadMovementOptions/MoveWorkloads.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/WorkloadMover.cs, src/ScaleUnitManagementTests/MoveWorkloadsTest.cs
Allows the user to select a scale unit that might be in a bad state and move everything from that scale unit to the hub, disregarding missing packages.
It has been tested that the movements are going through in AX.
Closes #107
=> Adds option to do emergency transition to hub

src/ScaleUnitManagement/WorkloadSetupOrchestrator/StorageAccountManager.cs
When the sas uri is created for the container the blob name is not specified. By setting the blob name, the sas uri can still be used to copy the blob.
#patch
resolves #116
=> Set the blob name in sas uri

src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/AOSClient.cs
Installing many large workloads can be very time consuming, and the AOS should not time out during these requests.
#patch
=> Increase timeout to 20 minutes

src/CLI/ManageWorkloadDataPipeline.cs, src/CLI/RootMenu.cs, src/CLI/UpgradeWorkloadsDefinition.cs, src/CLI/WorkloadDataPipelineOptions/DrainPipelines.cs, src/CLI/WorkloadDataPipelineOptions/StartPipelines.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/WorkloadDefinitionManager.cs
By using the MultiSelectMenu the user can choose a specific environment to perform the action on. This is useful if for example the drain succeeded on hub but not on spoke. Before, retrying would produce an error because the hub was already drained, but now drain can be retried only on the spoke. It is still easy to select all environments just by pressing enter in the menu.
Also, upgrade workloads now prints its progress to the user.
=> Allow choosing a specific environment to upgrade/drain/start workloads on

src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/AOSClient.cs
If there are no workloads or workload instances on the server, then the response from AOS will be null. This is now interpreted as an empty list.
Tested with single command execution.
Resolves #122
=> Turn null from AOS into empty lists #patch

src/ScaleUnitManagement/WorkloadSetupOrchestrator/ScaleUnitWorkloadInstaller.cs
We want to install workloads when they are in Ready state in Scale unit, otherwise upgrades and movement to spoke can cause problems. Since there is no _real_ workload versioning in the dev tools, we need to just overwrite on every install as we can't know what has changed without introspecting the hub workload versus what is installed in the scale unit.
#patch
Fixes #126.
=> Install workload in scale unit even if found Ready

src/ScaleUnitManagement/WorkloadSetupOrchestrator/AOSCommunicator.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/AOSClient.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/Utilities/ReliableRun.cs
Make sure that the AOS is warm whenever a new client is created.  Improve readability of errors caused by timeout.
#patch
resolves #106
=> Ping AOS whenever an AOSClient is constructed

src/ScaleUnitManagement/ScaleUnitFeatureManager/ScaleUnit/DisableDbAutoClose.cs, src/ScaleUnitManagement/ScaleUnitFeatureManager/ScaleUnit/SetAutoClose.cs
If auto-close is enabled on the spoke, it will not be able to operate properly. By turning it off during initialization this is avoided.
Tested on one-box environment. Verified that the auto-close property is turned off during initialization of the spoke.
closes #129
=> Turn auto-close off during initialization #patch

src/CLI/SetupTools.cs, src/CLI/WorkloadMovementMenu.cs, src/CLI/WorkloadMovementOptions/MoveWorkloads.cs, src/CLI/WorkloadMovementOptions/PerformEmergencyTransitionToHub.cs, src/ScaleUnitManagement/WorkloadSetupOrchestrator/WorkloadMover.cs, src/ScaleUnitManagementTests/MoveWorkloadsTest.cs
Print the name of every workload moved when initiating movements. Also inform the user if no workloads are moved, referring the user to see movement status.
closes #125
=> Print more details during workload movement #patch

src/CLI/Program.cs, src/CLI/Utilities/ArgumentHandler.cs, src/CLI/Utilities/ArgumentParser.cs, src/CLI/Utilities/Deployer.cs, src/CLI/Utilities/ScaleUnitDeployer.cs, src/CLI/Utilities/SingleBoxDeployer.cs, src/ScaleUnitManagementTests/ArgumentParserTest.cs
The user can type --hub-deploy or --spoke-deploy to run deployment for one of the scale units.
The deployer class is made abstract, and is implemented by the SingleBoxDeployer and the ScaleUnitDeployer.
=> Enable multibox deployment script
